### ISSUE TITLE
Check for debug log constant on init

### ISSUE THREAD

**Issue by blobaugh** [norcross/debug-quick-look#1]
If you check for the debug log constant in the init method before registering any hooks you will save resources and not need to fire the $this->check_debug_constant() in every method.

**Comment by norcross** [comment]
I think I follow. But it's set to show a warning if the constant isn't there (as opposed to just not loading at all). how would you approach it?

**Comment by blobaugh** [comment]
Leave that hook loading all the time because it is useful. Load the others when needed.

**Comment by norcross** [comment]
mind submitting a PR?

**Comment by norcross** [comment]
we actually addressed this (more or less) in v0.0.3 so gonna call this done.
