### ISSUE TITLE
set WP_DEBUG constants

### ISSUE THREAD

**Issue by norcross** [norcross/debug-quick-look#3]
determine how to check for the `WP_DEBUG` and `WP_DEBUG_LOG` constants and modify if required

**Comment by afragen** [comment]
Take a look at https://github.com/afragen/wp-debugging

It should give you a hint. BTW, it installs Debug Quick Look as a dependency.

**Comment by norcross** [comment]
Your ideas are intriguing to me and I wish to subscribe to your newsletter.

**Comment by afragen** [comment]
The question becomes whether to add it into this plugin or just recommend and use a plugin that has it built in. 

I hope you don’t mind but I unconditionally install and activate this plugin as well as Query Monitor in my plugin. 

If you take it for a spin, let me know what you think.

**Comment by norcross** [comment]
i’ve back-burnered this for a while, i’m gonna dive in this week and see what comes out of it.

**Comment by afragen** [comment]
Cool, can’t wait to see what you come up with.

**Comment by norcross** [comment]
decided I don't wanna mess with setting a config (for now). that may change later.
